### ISSUE TITLE
Support alternative auth for broker interaction

### ISSUE THREAD

**Issue by bmelville** [kubernetes-incubator/service-catalog#1019]
How do we support alternative auth support once the OSB proposal in https://github.com/openservicebrokerapi/servicebroker/issues/146 is addressed and available in the spec?

Likely there will be multiple different authentication mechanisms or serializations (e.g., JWT, Google Oauth2 JSON, etc.).

We'll kick off the conversation with a proposal for supporting the Google auth mechanism.

**Comment by bmelville** [comment]
Would like to see this land this quarter or as part of beta.

**Comment by bmelville** [comment]
@rifung

**Comment by arschles** [comment]
Ref #990, which is similar. I would recommend whatever change(s) fix this issue also fix that one simultaneously.

**Comment by nilebox** [comment]
We also interested in this issue.

For us the support for pluggable authentication implementation is critical. 

Our internal services use [own authentication mechanism](https://s2sauth.bitbucket.io/), JWT-based but not OAuth2. It could potentially be solved by something JWT-generic like https://github.com/kubernetes-incubator/service-catalog/issues/990, but I haven't looked in the details yet.

Auth plugins support would allow support for any vendor-specific protocol without including the code in the Service Catalog repo.
Auth plugins implementing REST API or RPC interface don't make sense though, and the extension should be configurable at the startup of Service Catalog. Since flags and declarative configuration is not enough (we need to inject the code implementing particular auth algorithm), my proposal is the following:

In the [server init method](https://github.com/kubernetes-incubator/service-catalog/blob/master/cmd/apiserver/app/server/server.go#L53) add arguments for plugin injection, simplified pseudocode:
```go
func NewCommandServer(..., auth *AuthPlugin) (*cobra.Command, error) {
  ...
}
```
This way anyone will be able to create their own application with `main` method constructing the Service Catalog server extended with plugins, build a Docker image of this application and use it instead of Service Catalog distribution provided out of the box.

Thoughts?

/cc @ash2k

**Comment by pmorie** [comment]
cc @deads2k @liggitt

**Comment by rifung** [comment]
@nilebox 

Are you saying that this AuthPlugin type would have sufficient information so that we know how to run auth code outside of the Catalog?

If I understand correctly, how would this work if you are using multiple brokers that use different kinds of auth? In the worst case, it could be multiple types of custom vendor specific auth.

**Comment by nilebox** [comment]
@rifung Yes, you understood correctly. For multiple brokers with different auth we could support multiple auth plugins, and have some field in `Broker` object like `spec.authType`, which will identify which auth algorithm/plugin to use for particular broker.

**Comment by nilebox** [comment]
@rifung the pluggability matches your proposal PR https://github.com/kubernetes-incubator/service-catalog/pull/1037 perfectly. `AuthInterface` could be the plugin interface, and `SecretType` would be the unique identifier of the plugin. Built-in plugins (basic auth and possibly others), could be registered the same way.

There is an alternative approach proposed by @liggitt in https://github.com/kubernetes-incubator/service-catalog/issues/990#issuecomment-315577090 - Service Catalog could support opaque token (with no specific of particular auth protocol in Service Catalog), and the separate process (provided by vendor) would generate and refresh the auth token in the secret.

I would like to discuss the design of alternative auth protocols support at the next Service Catalog design session on July 17, see the [agenda](https://docs.google.com/document/d/10VsJjstYfnqeQKCgXGgI43kQWnWFSx8JTH7wFh8CmPA/edit).

**Comment by rifung** [comment]
@nilebox Cool that seems good to me.

I think you said in the meeting you would do a PR for it so I look forward to seeing it! Note that @liggitt in #1037 pointed out the interface I defined isn't sufficient for x509 authentication. I don't know how important that is but if it matters then the interface needs to be updated to account for that.

**Comment by nilebox** [comment]
> I think you said in the meeting you would do a PR for it

I am going to do a design proposal and PR for opaque token support (see https://github.com/kubernetes-incubator/service-catalog/issues/990#issuecomment-315577090).

Plugin support is a separate concern, and we should probably postpone it until someone has an actual outstanding use case which is not solved by basic auth and opaque tokens.

**Comment by pmorie** [comment]
@bmelville - does the opaque token support address this issue?

**Comment by bmelville** [comment]
It does

**Comment by pmorie** [comment]
@bmelville okay - sounds like we should close this and open a new one if deeper integration with OAuth is desired.
