### ISSUE TITLE
Rename Binding to ServiceCatalogInstanceCredential

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#1033]
If we decide to remove PodPreset from Binding, the Binding resource no longer relates to the action of "binding" an app to a service instance. What it becomes is more akin to what CF calls a ServiceKey.

This name change is good for a variety of reasons:
- we've been overlooking an important usecase: a kube client asking for the credentials of a service instance w/o asking kube to bind it to an app.  This renaming helps with that by allowing people to ask for exactly what they want (the creds) w/o being confused by an unnecessary term like "binding".
- as we've been discussing, there will be lots of ways that people will want to "bind" or just "use" the creds from the service broker. In that vein, I think "binding" is too limiting a term, or more bluntly an incorrect term, at this point in the UX flow.
- If we do add some nice UX resources (like PodPresetBinding) I think putting the word "Binding" on those is more appropriate and more accurately describes what's going on.

So the overall flow would look like:
```
$ kubectl create -f svcInstance.yaml    # create mongoDB
$ kubectl create -f svcKey.yaml         # create a key/secret for the creds
$ kubectl create -f podpreset.yaml      # "bind" the key to my app
$ kubectl create -f myapp.yaml          # now deploy the app
```
Having the word/resource "Binding" at the 2nd step could be misleading and confusing to people.

Note that once we decide on our prefix this might become something like "ServiceCatalogKey".

**Comment by pmorie** [comment]
Can you put this suggestion on #1008 and close this one? We already have an issue for this.

**Comment by duglin** [comment]
ok I thought they were different enough to keep separate discussion, but let's try to resolve it in #1008.

**Comment by duglin** [comment]
per today's design call - I'm reopening this issue

**Comment by jzelinskie** [comment]
The major question for this thread is determining whether or not we want to maintain parity with CloudFoundry language (ServiceKey) or call this interaction something that makes more sense to Kubernetes.

From our discussion on call earlier, I think that Binding is more of process that can be composed of multiple interactions with Kubernetes resources, thus we shouldn't have a particular resource named Binding. Rather, we should have a few different resources that together form a set of interactions done in the Binding process. Because I see these as Kubernetes interactions that form a Binding, I think it makes sense to give them names relative to Kubernetes rather than adopting CloudFoundry terminology. I foresee future interactions that are a part of the Binding process, such as altering the PodSpec, that do not necessarily have parallels in the CloudFoundry world.

**Comment by duglin** [comment]
we agreed to ServiceCatalogInstanceCredential
move it to #1008

**Comment by nilebox** [comment]
@duglin rename the issue to "Rename Binding to ServiceCatalogInstanceCredential"? :)

**Comment by duglin** [comment]
@nilebox done :-)  a bit painful

**Comment by pmorie** [comment]
Closing; we will make #1080 the issue to record all discussion of API resource naming going forward.
