### ISSUE TITLE
Define limits of work

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1157]
At the F2F, we said that the controller should mark a particular generation of a resource reconciled when the controller is no longer doing work.  This implies that we should define what the standard approach to retries will be.  I believe CF implements:

- Exponential backoff
- Retry for up to a week (at least for {de}provision)

**Comment by staebler** [comment]
## Proposal: Limits of Work
The Controller should gracefully handle communication errors that prevent a resource from being successfully reconciled. In the event of a communication error, the Controller should retry the request after an exponential backoff. If the request continues to fail on retries, the Controller should stop retrying after a sufficiently long period of time. After the Controller stops retrying, the Controller should add the Failed condition to the resource with a status of True.

### Current Behavior Limitations
* The Controller does not set any condition on a resource when the retires are exhausted for reconciliation of that resource.
* When the Controller restarts or when a resource informer does a relist, the Controller will re-start the process of reconciliation for resources that have had communication errors. If the Controller had been waiting to retry reconciliation of the resource, then the exponential backoff will be started over. If the Controller had given up on retrying reconciliation of the resource, then the Controller will start again to reconcile the resource.

### Proposed Behavior
* The retry and backoff information will be stored in the status of the resource. They are currently stored in the Controller's queue of resources that need to be reconciled. If they are stored in the status instead, then they can persist through relists and restarts.
* The retry count will be replaced by a retry timeout. The Controller will retry the reconciliation for up to one week. After the first reconciliation failure (due to communications errors), the Controller will set the retry timeout to one week from the current time.
* When the Controller attempts to reconcile a resource that has an elapsed retry timeout, the Controller will instead add to the resource a Failed condition with a status of True.

### API Changes
The following fields will be added to `ServiceBrokerStatus`, `ServiceInstanceStatus`, and 
`ServiceInstanceCredentialStatus`.

```
// NextRetryTime is the next time that the reconciliation should be attempted
// for this resource.
// If NextRetryTime is nil, then reconciliation of the resource is not in a
// retry cycle.
NextRetryTime *metav1.Time `json:"nextRetryTime,omitempty"`
	
// RetryFailureTime is the time after which retries should no longer be
// attempted for this resource. After this time, the resource is considered
// Failed.
// If RetryFailureTime is nil, then reconciliation of the resource is not in a
// retry cycle.
RetryFailureTime *metav1.Time `json:"retryFailureTime,omitempty"`
```

**Comment by pmorie** [comment]
I'm not sure we need to or should store backoff information other than the deadline because it will be impossible to guarantee that the controller actually performs work at the next retry time, for example.

**Comment by staebler** [comment]
I've updated the proposal to retain the current way of doing exponential backoff rather than storing the exponential backoff information in the status of the resources.
