### ISSUE TITLE
Add String methods to our types for better logging / debugging

### ISSUE THREAD

**Issue by vaikas-google** [kubernetes-incubator/service-catalog#1393]
there's bunch of places where we construct the names for the types (ServiceClass, ServicePlan, etc.) in a form of a:
ServiceClass "NAMESPACE/NAME"
which is well and good, but since the NAME is a guid, it's pretty meaningless, so we have to tack in the ExternalName (aka, the name the Broker identifies this). So the string construction gets messy. We should have one place where we define this.

**Comment by n3wscott** [comment]
yessssssss

**Comment by n3wscott** [comment]
#dibs

**Comment by n3wscott** [comment]
From a comment: add String() string methods onto our types (ServiceInstance, ServiceBinding, etc...), we'll get this for free. See https://godoc.org/fmt#Stringer for why

**Comment by n3wscott** [comment]
On second thought, this is not going to be as simple as adding this to the types. Because the intent of Stringer is to make a readable version of Object -> String. But we want only a subset of the Object to be readable. So instead I am thinking of some logging helpers, here is an example:

https://github.com/kubernetes-incubator/service-catalog/pull/1403

**Comment by n3wscott** [comment]
And another WIP for fixing the k8s and external name junk we are trying to log:

https://github.com/kubernetes-incubator/service-catalog/pull/1408

**Comment by MHBauer** [comment]
@n3wscott @vaikas-google anything specifically left to do here? Looks like a lot of work has gone in, especially the pretty printer and support for a lot of our objects.

**Comment by n3wscott** [comment]
I think we can close it.
