### ISSUE TITLE
A potential issue with ObjectReference

### ISSUE THREAD

**Issue by ash2k** [kubernetes-incubator/service-catalog#1411]
Some time ago I created a ticket https://github.com/kubernetes/kubernetes/issues/49372 where `ObjectReference` was called "a mistake". So I thought maybe we shouldn't use this type as part of `ServiceInstanceSpec`, `BasicAuthConfig` and `BearerTokenAuthConfig` types?

> ObjectReference - this type was mistake, it's not correct for most use-cases and in other API areas we've chosen to make specific reference types with more correct information to better effect. I'm not strictly against this notion, but I'm definitely against moving this implementation.

I guess we need some guidance from API machinery folks.

/cc @deads2k

**Comment by nilebox** [comment]
> in other API areas we've chosen to make specific reference types with more correct information to better effect

Indeed, in many occasions we have already used specific types:
- [SecretKeyReference](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/apis/servicecatalog/types.go#L794)
- [PlanReference](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/apis/servicecatalog/types.go#L419)

But I'm not sure what is wrong with the`ObjectReference` and `LocalObjectReference` types apart from being part of `k8.io/api/core/v1` and not `meta/v1`?

Another example is using `runtime.RawExtension` for arbitrary JSON/YAML objects, which has an `Object` field we never use I believe, but still use this type as "recommended by apimachinery" according to https://github.com/kubernetes-incubator/service-catalog/issues/911.

**Comment by deads2k** [comment]
> But I'm not sure what is wrong with theObjectReference and LocalObjectReference types apart from being part of k8.io/api/core/v1 and not meta/v1?

1. `kind` is often fixed.  When it is fixed, it shouldn't be settable
2. `kind` is often wrong.  See HPA trying to refer to kinds when it really wants resources
3. `namespace` often isn't needed because only in-namespace refs are allowed or you point to cluster scoped things
4. `uid` isn't generally useful.  Sometimes it is, sometimes it isn't, but having to code defensively around it is unnecessary both for clients and for servers.
4. `apiVersion` is always wrong, since same named resources in the same group need to behave the same in a kube-like api
5. `resourceVersion` is never useful since you can't retrieve particular resource versions via the API
6. `fieldPath` is usually not useful, since very few places refer to particular fields.  In addition, they aren't fixed across versions, so the values are wrong

So we managed to get `name` correct, but every other field on the type is wrong :(

**Comment by pmorie** [comment]
The `ClusterServiceClassRef` field on `ClusterServicePlan` should just be a string field and should be called `ClusterServiceClassName`.

Curious to know where @deads2k comes down on other usages of the type in our API.

**Comment by deads2k** [comment]
In general, my bias is towards creating a struct for a reference.  Something like this.

```go
type ClusterServiceClassReference struct{
    Name string
}
```

This gives you a specific type that you can tune to your needs.  As I recall these types in particular, they have special naming constraints that may or may not allow different reference strategies.  Creating a separate struct gives more future options without pain.

**Comment by deads2k** [comment]
> In general, my bias is towards creating a struct for a reference. Something like this.

To be clear, I am strongly against using `ObjectReference` and `LocalObjectReference` in other APIs.  You should use specific types for your specific needs.

**Comment by pmorie** [comment]
Fields called 'Reference' should only refer to things via the k8s names, agree @deads2k ?

**Comment by deads2k** [comment]
> Fields called 'Reference' should only refer to things via the k8s names, agree @deads2k ?

That would have my strong recommendation.

**Comment by nilebox** [comment]
I'll make a PR for that.
