### ISSUE TITLE
Need to lock glide down to a specific version of etcd

### ISSUE THREAD

**Issue by staebler** [kubernetes-incubator/service-catalog#1594]
The glide.yaml file is currently requesting ^3.2.9 as the version of etcd. As with all our dependencies, we need to be specific about the version of etcd that we use.

We currently have `f1d7dd87da3e8feab4aaf675b8e29c6a5ed5f58b` in master. With the latest version (`694728c496e22dfa5719c78ff23cc982e15bcb2f`), the build breaks with this error.
```
# github.com/kubernetes-incubator/service-catalog/vendor/google.golang.org/genproto/googleapis/api/annotations
vendor/google.golang.org/genproto/googleapis/api/annotations/annotations.pb.go:40:10: unknown field 'Filename' in struct literal of type proto.ExtensionDesc
```

Also, there is a conflict in the version of etcd requested. The k8s.io/apiserver dependency is requesting `0520cb9304cb2385f7e72b8bc02d6e4d3257158a (v3.1.10)`.

**Comment by MHBauer** [comment]
I remember having a discussion about the v3.1.10 when https://github.com/kubernetes-incubator/service-catalog/pull/1570 was going in. We need a more advanced version to get the etcd embed (and even that embed has been improved in v3.3 seriesof etcd).

It was set to v3.1.10 in the testing
https://github.com/kubernetes-incubator/service-catalog/blob/1ce5c4d91c94b68305232b40ed9add9105f5abf3/pkg/kubernetes/hack/lib/etcd.sh#L19

Since we have `f1d7dd87da3e8feab4aaf675b8e29c6a5ed5f58b`, should we hardcode that and leave a comment for the future? Move to 3.3? 

As far as apimachinery goes, they're still set for 3.1.10 for the 1.9 release.

**Comment by MHBauer** [comment]
we have moved from glide to dep, and we're constrained to a particular release of etcd
https://github.com/kubernetes-incubator/service-catalog/blob/v0.1.21/Gopkg.toml#L29-L35
