### ISSUE TITLE
Consensus on support for user-specified namespaces

### ISSUE THREAD

**Issue by bmelville** [kubernetes-incubator/service-catalog#162]
Throughout the code, namespace support is either hard-coded to "default", or passed around using "space_id" field. This needs to be supported in a standardized way in the model and code.

**Comment by arschles** [comment]
The namespace is hard-coded for a variety of purposes. One of them is to determine where to write bound credentials, and this is an easy one. Instead of hard-coding, let's just use the namespace from the binding itself. There are other places where a namespace is hard coded for other purposes, and those will require additional discussion, but my previous is a good start.

**Comment by pmorie** [comment]
Closed by #262
