### ISSUE TITLE
Race in integration tests

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1625]
Looks like #1611 introduced a new data race in the integration tests:

```
    --- FAIL: TestDeleteServiceInstance/deprovision_instance_after_in_progress_provision (10.90s)
    	framework.go:76: Starting server on port: 4184
    	controller_test.go:479: controller start
    	controller_test.go:491: informers start
    	framework.go:72: Shutting down server on port: 4184
    	testing.go:699: race detected during execution of test
	testing.go:699: race detected during execution of test
```

Looking into this now.

**Comment by MHBauer** [comment]
#1626 commented out the test.

**Comment by MHBauer** [comment]
There is an issue with the way the controllerTest framework is written. When `controllerTest.Run` is called, it runs the `setup` func from the testcase, or otherwise previously defined. This func is run AFTER the controllers have been setup and are running. I am not sure if this is what is being hit, but I've hit it while trying to modify the cases and controllers.

**Comment by MHBauer** [comment]
From what I can see it's mostly due to `prependActions` being called after the controllers have been started. We can't modify what the controller is to return after we start it. Right now we're very aggressively tied to the internals of the reconcilliation loops as well as the watchiness of the controller interaction with the various clients.

**Comment by MHBauer** [comment]
I wish I had more carefully checked the PR that merged the new framework and tests. I'm not sure there's a way forward that's some small move. It's either a huge rewrite and shift, or back it out and go in another direction. 

@staebler might have the solution with the Dynamic reactions, but I am very unconfortable with us modifying the state of the controllers after starting them.

**Comment by staebler** [comment]
I agree that the `setup` function should not be used to modify the state of the controllers. The `setup` function is used to modify the responses from the external resources to which the controllers make requests. The assumption is that, when the controller starts, there is nothing queued for the controllers until after the `setup` function is called. Consequently, the controllers have no work to do and should not be making any requests of external resources. I think that is a fair assumption. But if things have changed that make that assumption no longer valid, then we may indeed need to reconsider how setup is being done for integration tests.

**Comment by MHBauer** [comment]
I disagree with `The assumption is that, when the controller starts, there is nothing queued for the controllers until after the setup function is called.`.

**Comment by MHBauer** [comment]
That breaks the 'push a bunch of yaml and let the system figure it out' idea.

**Comment by staebler** [comment]
I disagree with that. These are tests. The "yaml" isn't pushed until after the setup.
