### ISSUE TITLE
Add option to display plan schemas in svcat

### ISSUE THREAD

**Issue by martinmaly** [kubernetes-incubator/service-catalog#1720]
Currently it doesn't seem possible in `svcat describe plan` to show full detail of the plan, specifically schemas for provisioning and/or binding.

Would it be possible to add support for such detailed output?

**Comment by carolynvs** [comment]
@martinmaly Is that information currently returned by the service catalog api? I'm not quite familiar with what you mean by schemas.

**Comment by martinmaly** [comment]
I believe so; when I run `kubectl get clusterserviceplans <GUID> -o yaml` and the service plan contains schema (as per https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#schema-object) the `kubectl` will print whatever schema the broker provided.

I guess kubectl will just print the whole resource as yaml so having a full resource yaml output in svcat would suffice.

**Comment by carolynvs** [comment]
Nice! I didn't know about the optional schema (because OSBA doesn't return them yet). 

There is definitely value in having the schema printed out by default. Would you be interested in working on that? I'd be happy to help.

Maybe something like this?

```console
$ svcat describe plan standard100
  Name:          standard100
  Description:   Standard Tier, 100 DTUs
  UUID:          edc2badc-d93b-4d9c-9d8e-da2f1c8c3e1c
  Status:        Active
  Free:          false
  Class:         azure-mysqldb

Instances:
No instances defined

Instance Parameter Schema: (if defined)
...

Binding Parameter Schema: (if defined)
...

```

That said, a yaml dump flag would also be useful too. I'm just all for making the UX for svcat shine, so I'd like to see us improve the default command output as well.

**Comment by kibbles-n-bytes** [comment]
@carolynvs I'm happy to take a crack at this!

**Comment by carolynvs** [comment]
@kibbles-n-bytes Hurray!
