### ISSUE TITLE
How do we efficiently look up bindings to a given instance?

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#177]
Our current API server design allows the user to specify one of the behaviors on a DELETE operation for an instance:

1. Force delete all bindings that point to the instance (i.e. a cascading delete)
1. Fail if there are any bindings to the instance

In the data model, bindings point to instances, but not the other way around. This model doesn't give us an efficient way to look up bindings for a given instance, but we'll need that functionality to implement both cases in a resource-efficient (and fast) way.

I propose that we build an index for bindings, using the binding's instance (specifically, the fully-qualified path to the instance) as the only key in the index.

In an TPR-based data store (which we're going to ditch), we'd implement this with labels. Since we're using etcd directly, we should do something similar.

**Comment by pmorie** [comment]
Iterate through them.

**Comment by pmorie** [comment]
Efficient is not a goal here

**Comment by duglin** [comment]
when you say "build an index", do you mean create a new resource in the model to hold this info/link?

**Comment by duglin** [comment]
Or are you proposing that we add a label to the binding that points back to the instance since filtering/searching by labels is really the only searching mechanism k8s offers us today?

**Comment by arschles** [comment]
@pmorie - you cool with revisiting this issue after MVP1? I don't think iterating through all bindings (in all namespaces) is a viable long term solution

@duglin I'm proposing the latter

**Comment by duglin** [comment]
@arschles +1 to the label. I agree that iterating over potentially YUGE number of bindings isn't good. We might as well just bite the bullet now.

**Comment by krancour** [comment]
+1 to the label and to tackling now.

Registering one minor concern, however... nothing really stops a user from editing or removing a label and doing so would undermine this strategy.

**Comment by pmorie** [comment]
I finally have a moment to write a statement on this now that I've spoken to people on slack.

I think we have had a mismatch here, originating from a discussion I had long ago with @duglin, so I will demystify here.  There are two different concerns in play:

Concern 1:  

@duglin wants to know how to query resources on field selection.  Here's an explanation of the pattern we have for implementing this in k8s:


The listable fields for a resource are a function of that object's etcd storage.  Here's the sketch, with links into the implementation for pods:

1.  There is an interface called [`storage.Interface`]() that is implemented for each resource type.
2.  Most resources do not fully implement this, because there is much shared code; instead they use the [generic store](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/generic/registry/store.go#L48) type to get the common functionality and implement a few different [`Strategy`](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/rest/create.go) interfaces in their own [strategy type](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/strategy.go#L43)
3.  There is a resource-specific package called `etcd` with a type that implements the etcd-backed REST storage for a resource, which embeds the generic store, and has a [`NewStorage`](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/etcd/etcd.go#L60) factory method to build a new storage for that type
4.  The generic store has a [`PredicateFunc`](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/generic/registry/store.go#L90) field which is a function that determines [which resources](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/strategy.go#L169) should be returned for a `List` call
5.  The client interface for a resource has a [`List` method](https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/pod.go#L41) with a `ListOptions` parameter; this is turned into a field selector inside the REST storage and applied to `PredicateFunc` for users of the generic store

Concern 2:

@arschles is concerned about finding bindings for a given instance when that instance is deleted.  I think we discussed two possible behaviors here.

First, you could validate and reject deletions if bindings still existed.  This validation would be implemented in an admission controller.  Admission controllers allow you to use the same informer infrastucture that we will use in the 'service catalog controller'.  You can maintain an indexed cache using that informer infrastructure and have the information ready to validate against.

The second behavior was a cascading delete, implemented by the controller with API-level finalizers, which would use the same 'maintain a cache of the information' approach as the admission controller.

Hope that clarifies things -- sorry for the mismatches on this subject.

**Comment by arschles** [comment]
@pmorie I'm assuming the admission controller sits in the critical path of the API call - this seems to be the general k8s design. If I'm right, will that index live in-memory on the API server?

**Comment by pmorie** [comment]
@arschles Yep, in an admission controller currently all of the controller's memory lives within the API server.

**Comment by pmorie** [comment]
Closing; if we do this in an admission controller we should just use the informer infrastructure
