### ISSUE TITLE
Add zsh completion to svcat

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-incubator/service-catalog#1912]
Now that we have bash completion in svcat, we need zsh next!

```
svcat completion zsh
```

I believe that spf13/cobra has support for zsh on master (not sure if it's an official release), so that's worth investigating and possibly bumping our version to get that for free. Otherwise, let's see how kubectl does it and follow their lead.

**Comment by kikisdeliveryservice** [comment]
@carolynvs 
So I looked into this issue and can confirm that the latest release of cobra has zsh completion.
Service catalog is currently using a version of spf13/cobra from July 22, 2016(https://github.com/kubernetes-incubator/service-catalog/blob/5c43dec9f1cb3966d2dc2e643511371d2458b858/Gopkg.lock) which is prior to the first release 0.0.1 in Oct 2017.  There is also a second release: 0.0.2 from March 29th.  (See release page: https://github.com/spf13/cobra/releases)

I also checked to see what kubectl is doing and they are using spf13/cobra version 0.0.1, which has the zsh support: https://github.com/kubernetes/kubectl/blob/fe5aff0d65d5428bbe281ef2f2cae95652150712/Gopkg.lock and also see here: https://github.com/kubernetes/kubernetes/blob/0207a090743398608b357264ab4c27aeea864abc/pkg/kubectl/cmd/completion.go

So we might consider bumping the version and then addressing this issue?

If this sounds good, I can:
1. open a new issue for bumping the cobra version to support zsh and to get group feedback on that. 2. if you like, I can try doing that PR for the bump since I was able to find some examples of that in the k8s repo. 
3. once that's done I can address this issue (zsh completion) with its own PR

Please let me know your thoughts on this. Thanks!

**Comment by carolynvs** [comment]
I am fine with bumping and adding the feature in the same PR.

**Comment by kikisdeliveryservice** [comment]
@carolynvs Will do. Should I bump to 0.0.1 or 0.0.2?

**Comment by kikisdeliveryservice** [comment]
Ok I'll try 0.0.2!
