### ISSUE TITLE
svcat should allow lists in --param

### ISSUE THREAD

**Issue by kibbles-n-bytes** [kubernetes-incubator/service-catalog#1987]
Our broker requires a parameter that is a list for every binding type, which doesn't play too nicely with svcat and requires us to use `--params-json`. `svcat` should have an easier method for passing a parameter that is a list.

Was talking to @n3wscott offline, and an easy first step would be to have duplicate keys merged into a list. So you would do `--param foo=bar --param foo=baz`, and it'd get sent as `{ "foo": ["bar","baz"]}`. I wanted to check if that is something that has precedent in other CLI tools.

@carolynvs Thoughts? I had also considered `--param foo=bar,baz`, but this syntax seems to be interpreted as `--param foo=bar --param baz`. And the same problem happens with `--param foo=[bar,baz]`, plus complications surrounding if the user actually wanted to send a string with brackets, and possible shell special character conflicts.

**Comment by carolynvs** [comment]
I think the repeated parameter, with the same key being combined into an array has the least ambiguity.

We can easily support that, the changes would need to be made here:

https://github.com/kubernetes-incubator/service-catalog/blob/06ffe5324fba207c017e91fad028f0de6051a80a/cmd/svcat/parameters/parameters.go#L40-L44

So that instead of returning a map[string]string, we return map[string]interface{} and then handle consolidating repeated keys.

**Comment by n3wscott** [comment]
Agreed with `map{colors: [red, blue]}`

**Comment by teaguecole** [comment]
im going to take this one
