### ISSUE TITLE
ServiceCatalog floods brokers when provisioning is permanently not possible.

### ISSUE THREAD

**Issue by mszostok** [kubernetes-incubator/service-catalog#2006]
Hi all :)

_This is a nutshell of our issue:_
The flow of the ServiceInstance provisioning was changed after refactoring (https://github.com/kubernetes-incubator/service-catalog/pull/1886). Now the Service Catalog has infinite loop
```
start provisioning -> fail, requires orphan mitigation -> perform orphan mitigation 
-> start provisioning -> …
```
it will do so until it finally succeeds.

_Details_

Scenario - Service Catalog version 0.1.3 - **correct flow**
1. The Service Catalog triggers provisioning of given ClusterServiceClass
2. We are responding with http code **202 (Accepted)** and triggering asynchronous operation which fails because of some reason.
3. When Service Catalog calls _last_operation_ endpoint we are returning http code **200 (OK)** with body 
```json
{
  "state": "failed",
  "description": "Cannot provision instance. <reason>"
}
```
 4. Service Catalog marks the ServiceInstance as failed, sets `Deprovision Request` as **Required** and **does not perform any additional actions**. When we call deprovision on such failed instance the Service Catalog sends deprovision request also to the broker.

Scenario - Service Catalog version 0.1.11 - **broken flow**
1. Steps 1-3 same as above.
4. Step 4: Service Catalog marks the ServiceInstance as failed, sets `Deprovision Request` as **Not Required** and **does not perform any additional actions**. 

When we call deprovision on such failed instance the Service Catalog does not send deprovision request to the Service Broker, so you created a ticket to fix this https://github.com/kubernetes-incubator/service-catalog/issues/1879 but PR which should fix that https://github.com/kubernetes-incubator/service-catalog/pull/1886, caused something more. Now the Service Catalog in versions above the 0.1.11 has infinite loop
```
start provisioning -> fail, requires orphan mitigation -> perform orphan mitigation 
-> start provisioning -> …
```
This loop "spams" our brokers because there are no delays and max retries. In some cases such approach breaks our flow. 
We can also consider an example when someone has a Azure Service Broker and wants to provision a db service. Instance can failed e.g. because the quota in given namespace was exhausted. So repating describe action over and over does not make sense.

The question is, why are you performing the orphan mitigation if Service Broker responded with **200 (OK)** status code?

In spec https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#orphans, we can find that in such case you shouldn't do that.

Could you elaborate about your new approach for provisioning? Because I cannot find any documentation about it in the Service Catalog. 
What's more in my opinion you should restore the previous behaviour (from version 0.1.3). When Service Broker respond with 200 status code on _last_operation_ endpoint with body 
```json
{
  "state": "failed",
  "description": "Cannot provision instance. <reason>"
}
```
you should only mark this ServiceInstance as failed and stop pooling. Then when user sends deprovision request you should call the Service Broker. Thanks to that the given Service Broker will perform a deprovision action (same kind of garbage collector) for failed instance.

Thank you in advance

**Comment by nilebox** [comment]
Also, to clarify the scope of the issue: by "when provisioning is permanently not possible" in the title it is implied that platform should either treat any async provisioning failure as a permanent one, or be able to determine whether a failure is temporary or permanent.

Unfortunately, with OSB API v2 it is impossible for the platform (Service Catalog) to know whether the failure is temporary or permanent. OSB broker just returns `state: failed` in the response to `last_operation`, there is no error categorization. This is definitely something we should address in `v3` (or as a backward compatible optional field in `v2`), but currently we have to deal with what we have.

In 0.1.3 Service Catalog treated any failure as permanent. It was a general agreement that this was a flaw in the Service Catalog code that had been justified by our focus on beta release that only supported the "happy path" well. Since beta was released, we invested a lot of effort to improve coverage of "non-happy path", see issues filtered by `non-happy-path` label for example: https://github.com/kubernetes-incubator/service-catalog/issues?utf8=%E2%9C%93&q=label%3Anon-happy-path+

I hope that helps.
Please do report any bugs you might find.

**Comment by mszostok** [comment]
@nilebox Thank you for you reply. It helps a lot!


Now we know that this behaviour is by design. Previous comment was based on version 0.1.12, but now I can see that v0.1.17 is the newest one, so we will validate the new flow one more time. If we find the same problems, we will look into the code and report issue with the details.

PS. _Sorry for such late response but last week I was at conference and vacation._
