### ISSUE TITLE
advertise checksums of svcat downloads

### ISSUE THREAD

**Issue by mrgleeco** [kubernetes-incubator/service-catalog#2029]
I can appreciate the convenience of downloading the CLI from https://download.svcat.sh/cli/latest

But really, what is in that 26MiB binary i just downloaded from this random URL?  Published sha checksums would be a simple step to make these warez feel more legit 

ps - listing/linking each version is also quite helpful

**Comment by carolynvs** [comment]
The downloads are served from a HTTPS only endpoint, and since the checksum would also be served from the same source, there isn't value to providing checksums beyond verifying that the file downloaded completely. If there were mirrors of our downloads, that would be a different matter.

I am closing this since I don't see the attack vector or value in providing the checksum, and don't intend on adding this functionality. Please leave a comment if I am missing something.

> listing/linking each version is also quite helpful

You can download specific versions from https://download.svcat.sh/cli/VERSION, where version is a release number from our releases page.
