### ISSUE TITLE
Left navbar doesn't scroll properly on the docs site

### ISSUE THREAD

**Issue by shubheksha** [kubernetes-incubator/service-catalog#2352]
# Bug Report 

**What happened**:
The navbar on the left on the docs site doesn't scroll properly, it seems fixed at one point.

**What you expected to happen**:
The navbar should scroll along with the rest of the page.

**How to reproduce it (as minimally and precisely as possible)**:
Scroll to the bottom of https://svc-cat.io/docs/resources/

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/7693422/45814798-60fc7500-bcf4-11e8-9f23-42ca18e5137e.png)

(edit from Carolyn): Here's the docs on how to work with our documentation site: https://svc-cat.io/docs/devguide/#documentation

**Comment by arief-hidayat** [comment]
#dibs

**Comment by arief-hidayat** [comment]
hi @carolynvs ,
I'd like to start my first contribution here.
I have question. 

Why do we need to make different UI behaviour (left navbar) compared to kubernetes docs? e.g. https://kubernetes.io/docs/concepts/services-networking/service/
Would it be better to standardise among all kubernetes docs page?

thanks

**Comment by arief-hidayat** [comment]
while waiting for your answer on the above, I have implemented javascript change to recalculate:
* css top position of the left menu, instead of just fixed it to a constant.
* css max-height, to make sure it doesn't overlap with the component below it (footer).

@carolynvs 
Please let me know if you prefer this approach. I will then raise PR.

**Comment by arief-hidayat** [comment]
Seems like Carolyn is busy. @jberkhahn @mhbauer could you answer my question above? Thanks

**Comment by carolynvs** [comment]
@arief-hidayat I've stepped down from the Service Catalog project, but @jberkhahn or @jboyd01 should be able to help.

**Comment by jberkhahn** [comment]
Carolyn made it that way because she thought it was a better design, as expressed above. I also prefer it so you can jump around without having to scroll all the way back to the top.

There's no hard and fast requirement for us to behave exactly the same as the core Kube docs as far as I know. I would like it if it couldn't jump out of the frame, though.

**Comment by arief-hidayat** [comment]
Thanks @jberkhahn .
I'll proceed with raising the PR then.
