### ISSUE TITLE
makefile changes for glide

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-incubator/service-catalog#259]
makefile needs to run `glide update` when the yaml changes, and `glide install` when the lock changes. 

I need one of the makefile wizards to help me do that.

**Comment by duglin** [comment]
Need more background/info on glide first... I assumed glide.yaml is something a dev might modify to change which version of a repo we use.  And glide.lock is a generated file but would only be changed, by glide, if someone changed glide.yaml.  Is this not correct?

if it is when would glide.lock be changed but glide.yaml not?

**Comment by MHBauer** [comment]
in theory, I think you could do a manual `glide update` which could pick up a newer version of something (if we specified versions as a range). This would impact the lock without impacting the yaml.

Another way is, I feel I need to 'clean' my environment, so I manually delete `vendor/` and lock. When we run an install, it'll run an update. So, I suppose you could say that a 'clean' should rm the lock file too. 

I think most of the glide invocations should be done by the user, not tooling. The way it is now, someone changes the yaml, and it does the wrong thing, unless you've deleted the lock. At which point, you have to manually go in an futz around anyway. Maybe this is an upstream problem? If the yaml has changed, glide should just do the right thing rather than blatantly ignoring it's own warning.

**Comment by krancour** [comment]
Perhaps stating the obvious here, but level-setting. `glide.yaml` is an expression of _intent_: "Here are the things I want." `glide.lock` is a manifest of what you _got_.

`glide install` installs exactly what is in the `glide.lock`. This is what makes it possible for every contributor to get _precisely_ the same versions of each dependency as the next contributor. In the edge case where `glide.lock` doesn't exist, `glide install` automatically runs `glide update` instead.

`glide update` uses `glide.yalm` (your intent) and your source code to resolve all your dependencies (resolves transitive dependencies, too) and records the exact version used of each package in `glide.lock`. Unless otherwise constrained by your intent (i.e. unless you've specified a version or version range) It will take the _latest_ available version of each package (i.e. head of master).

One last bit of info, which is really critical. There's a value in `glide.lock` that's a digest of `glide.yaml`. If you try to run `glide install` and the digested `glide.yaml` doesn't match the digest value that is stored in `glide.lock`, glide will warn you that you need to run `glide update` instead.

What I'm getting around to is that modifying `glide.yaml` and then running `glide update` (or `glide get github.com/yada/yada`) is the correct way to either add new dependencies to a glide project or modify existing dependencies (e.g. specify a different version range).

@MHBauer is correct that our build process lacks the ability to distinguish the scenario where it should run `glide update` instead of `glide install`. But a reminder, the scenario where you do thatis when `glide.yaml` has been updated and the `glide.lock` and `glide.yaml` don't match. Let me be clear that a `glide.yaml` and `glide.lock` that don't match one another should never be checked in together-- that's an invalid condition.

So, I think what this _really_ all boils down to is that we need a way for developers to _manually_ execute `glide update` any time they have modified the `glide.yaml` so that they can commit the updated `glide.lock` along with the updated `glide.yaml`.

If you're the sort who eschews containerized processes, then just manually run `glide update`.

For the rest of us, I think it's imminently practical to add a make target that runs `glide update` in the build container. In fact, @arschles and I are accustomed to including such a target in most of the Deis projects we have worked on to date.

Not unrelated... we've also found it useful to provide a make target (something like `make dev-env`) that dumps you in an interactive bash shell inside the build container. This allows you to explore and experiment in the containerized development environment and allows you to run arbitrary commands like `glide update`, should you need to. (Not that I don't still advocate that having it's own dedicated make target.)

Does this all make sense / sound reasonable? Happy to tackle this. It's just minutes of work.

**Comment by MHBauer** [comment]
SGTM.

Stated much more specifically and correctly than I. The dev-env sounds useful, and the glide update target sounds like something we may need in the future.

**Comment by duglin** [comment]
Morgan, I'm not sure of your exact scenario, but can you try this to see if it fixes it:
```
.init: $(scBuildImageTarget) glide.lock glide 

glide:
    ! [ .init -ot glide.lock ] || $(DOCKER_CMD) glide install --strip-vendor
    touch .init

glide.lock: glide.yaml
    $(DOCKER_CMD) glide update --strip-vendor
    touch .init
```

**Comment by pmorie** [comment]
@MHBauer is this still an issue?

**Comment by MHBauer** [comment]
Haven't tried dug's thing. Looks like it could work. I've since learned a lot about make.

This is mainly a contributor-experience issue.

**Comment by pmorie** [comment]
Moving to Later because no one seems blocked by it and MVP-1 is overdue.

**Comment by arschles** [comment]
#620 will obviate this issue. Closing
