### ISSUE TITLE
Gather use cases for Service Producers

### ISSUE THREAD

**Issue by slack** [kubernetes-incubator/service-catalog#27]
This issue will be a bucket to hold use cases focused on issues service producers are facing. After we have a solid set we can organize them into a document and review in a sig meeting.

**Comment by pmorie** [comment]
Off the top of my head, a couple basic ones:

1.  As an operator of an existing service broker, I want my broker to be usable from the Kubernetes service catalog, so that I can widen my user base
2.  As a Kubernetes user, I want to be able to run my own service broker so that I can join the SB ecosystem
3.  As a Kubernetes user, I want to be able to run my own service broker so that I can share services in my namespace with users in other namespaces

**Comment by duglin** [comment]
For service providers, I think most of my thoughts focus on making their life easier w.r.t. creating brokers. So, offering sample/template service brokers would be good so users can just plug-in their specific code when asked to provision/bind.

I guess if we assumed a very simplistic model of a K8s service == one of our service instances, such that a provision call is just deploying another instance of a K8s service then creating a SB resource type might be good, where one of the fields points to the K8s service that's meant to be deployed. 

Of course, where it is deployed is interesting. If its deployed into the end-user's namespace I kind of wonder why they would use the SB model at all. It seems to me the benefit the SB model is that someone else is hosting it. 

Just some random thoughts...

**Comment by arschles** [comment]
As discussed in yesterday's SIG meeting, I think we should include the following use case:

- I am an owner of a SaaS product
- I want to allow any Kubernetes cluster operator to add my services to their cluster's catalog
- I have not built a CF service broker to interoperate with my SaaS product

**Comment by pmorie** [comment]
I think we have covered this one in spirit well enough for now that I'm comfortable closing the issue.

**Comment by pmorie** [comment]
Closing for now as out of scope.
