### ISSUE TITLE
Make the API server health check fail until after all TPRs have been created

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#464]
When the API server starts up, it checks for available third party resources. When the TPRs already exist, the server begins serving almost immediately.

But when they don't already exist, the pod is listed as Ready, but it is not actually listening on a port. The HTTP health check endpoint for the API server should not return 200 (indicating to Kubernetes that the pod is ready) until all TPRs have been confirmed created and ready.

cc/ @simonleung8

**Comment by simonleung8** [comment]
#dibs

**Comment by arschles** [comment]
@duglin assigning this to you since I can't assign to @simonleung8

**Comment by simonleung8** [comment]
@arschles This issue is resolved.

`genericapiserver` installs health check on [PrepareRun()](https://github.com/kubernetes/kubernetes/blob/6b9a9442855d16e0ff0c02ab0c82b1c1665cccaf/pkg/genericapiserver/genericapiserver.go#L186), the pod will report healthy as long as TPR installs successfully and apiserver starts.

**Comment by arschles** [comment]
thanks @simonleung8. closing
