### ISSUE TITLE
Helm chart doesn't follow best practices for specifying namespace

### ISSUE THREAD

**Issue by krancour** [kubernetes-incubator/service-catalog#56]
The Helm chart found in the `deployments` dir configures namespaces through `--set` or a `values.yaml`. This is not how Helm charts are recommended to be written. The recommendation is that `namespace:` be entirely omitted from the metadata for each resource. Operators should specify a namespace when installing a chart by using the `--namespace` flag.

**Comment by pmorie** [comment]
I can't assign this to @krancour yet, but he's working on this one.

**Comment by martinmaly** [comment]
Thanks for the suggestion on Helm best practices! As I was learning Helm I discovered the recommendation to use --namespace flag and not use namespace: clauses in the chart.

Strangely enough, in another branch of the initial seed code we needed a Helm chart which would deploy into multiple namespaces (default and catalog) which is not possible otherwise. Of course, that use cases doesn't apply to this incarnation of the chart so it is possible to clean it up.
