### ISSUE TITLE
Move top-level Go code under the 'pkg' directory

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#58]
This directory structure follows what kubernetes/kubernetes does. We may have other directories in the future that have Go code in them, but this issue starts with moving code just to `pkg`

cc/ @pmorie

**Comment by pmorie** [comment]
Agree that we should do this.

**Comment by martinmaly** [comment]
Will all import paths then need to include "pkg" or is "pkg" directory somehow special in that it gets auto-resolved during golang package resolution?

**Comment by pmorie** [comment]
Yep, all import paths need to include the full path.

**Comment by martinmaly** [comment]
do we want to do that? pollute all paths with pkg?

**Comment by pmorie** [comment]
@martinmaly Many go projects do this -- Kubernetes is one.

**Comment by arschles** [comment]
for context, one of the reasons I created this issue is to move our codebase closer in structure to that of kubernetes/kubernetes

**Comment by vaikas-google** [comment]
One thing to keep in mind is (I'm not saying this is the case here) could be 'legacy' reasons. There might be a good reason to do something that way, but sometimes it could be that 'we really should be doing it different way but we're stuck for now'. So, if we could for some of these (bit painful imho) moves/renames validate that this is the current _and_ future direction, then I'm more inclined to do it. Just doing it because k8s has been doing it that way might just mean we have to clean things up later.
According to go code doc:
https://golang.org/doc/code.html

src contains Go source files,
pkg contains package objects, and
bin contains executable commands.


So if we can figure out why k8s (seemingly?) deviates from this I'd be more inclined to proceed or mayhaps I'm missing something.

**Comment by arschles** [comment]
looks like this is already done, closing
