### ISSUE TITLE
Some little issue for helm chart and walkthrough doc

### ISSUE THREAD

**Issue by mdshuai** [kubernetes-incubator/service-catalog#625]
1. etcd image is hardcode in [apiserver-deployment.yaml](https://github.com/kubernetes-incubator/service-catalog/blob/master/charts/catalog/templates/apiserver-deployment.yaml#L85), better make it configurable in values file like [apiserver](https://github.com/kubernetes-incubator/service-catalog/blob/master/charts/catalog/values.yaml#L4)
2. [ups-broker valuels file](https://github.com/kubernetes-incubator/service-catalog/blob/master/charts/ups-broker/values.yaml) format better aligned with [catalog values file](https://github.com/kubernetes-incubator/service-catalog/blob/master/charts/catalog/values.yaml) (just my opinion, if you think it's ok, ignore it)
3. In the walkthrough doc [step4](https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/walkthrough.md#step-4---install-and-configure-kubectl-16) 
>kubectl config set-cluster service-catalog --server=http://$SVC_CAT_API_SERVER_IP:30080
Note that you'll need to determine the service IP of the service catalog API server, and substitute that for $SVC_CAT_API_SERVER_IP.

30080 is a node port not service port.
```
[root@ip-172-18-13-114 kubernetes-incubator]# kubectl get svc -n catalog
NAME                        CLUSTER-IP   EXTERNAL-IP   PORT(S)                      AGE
catalog-catalog-apiserver   10.0.0.254   <nodes>       80:30080/TCP,443:30443/TCP   15s
```

**Comment by arschles** [comment]
@mdshuai what is the status of this issue? if you have started working through it, I will leave it in 0.0.2. Otherwise, I am going to bump it

**Comment by krancour** [comment]
> etcd image is hardcode in apiserver-deployment.yaml, better make it configurable in values file like apiserver

The etcd that's included is inadequate for production use since it's not HA. You'll note that there is an attribute under `apiserver.storage.etcd` called`useEmbedded`. If you set that to `false`, you can further specify the location of etcd server(s) using the `servers` attribute.

I'm mentioning this only because I perceive the etcd that you can embed in the apiserver's pod as _strictly_ for "kicking the tires." That being the case, when I originally wrote this chart, I considered it unimportant to make the etcd image configurable. (As a general principle, I try not to provide people with more options than they need.)

I'm sure some counterarguments could be made. I just wanted to articulate the rationale.

> ups-broker valuels file format better aligned with catalog values file (just my opinion, if you think it's ok, ignore it)

They're not out of alignment...

The `catalog` chart is comprised of two high-level components-- the apiserver and the controller-manager, so `apiserver` and `controllerManager` are, hierarchically, the topmost levels of that configuration tree. Immediately under it, you see attributes like `image` and `imagePullPolicy`...

The `ups-broker` chart, by contrast, isn't comprised of multiple high-level components. It would be redundant to group all of its attributes under some construct like `upsBroker`, so that is omitted.

What remains consistent between the two values files, however, is how attributes are named. e.g. You will see `image` and `imagePullPolicy` attributes in the ups-broker's values file that align nicely with the attributes by the same name under `apiserver` and `controllerManager` in the catalog's values file.

I believe this is adequately consistent.

> 30080 is a node port not service port.

The doc doesn't say "service port." It says "service IP." But I agree that term is vague at best and that particular section could benefit from a rewrite.

**Comment by arschles** [comment]
Looks like documentation can solve much of this issue. I am moving into 0.0.3

**Comment by arschles** [comment]
I am moving this out of a milestone because it's unclear what documentation is necessary to add. @mdshuai can you comment on what docs would help resolve the questions you posed in the OP?

**Comment by duglin** [comment]
@mdshuai is this still an issue? If not, or if we don't hear from you we may close this issue.
