### ISSUE TITLE
Decide how we should support alpha fields in non-alpha resources

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#753]
There are a number of needs for having alpha fields in non-alpha resources:

1.  We should not have non-alpha fields for things that are alpha features in Kubernetes (`PodPreset`)
2.  We should be able to support features that are accepted to the OSB spec but not yet released (parameter schema)
3.  We should be able to add our own alpha features that are not (1) or (2)
4.  We want to be able to release our beta API with fields that are still alpha

We should eventually do what kubernetes upstream does.  There is a [proposal](https://docs.google.com/document/d/1wuoSqHkeT51mQQ7dIFhUKrdi3-1wbKrNWeIL4cKb9zU/edit#heading=h.3sjjx2gvn9hz) (you must join the [sig api machinery group to view](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-sig-api-machinery) for adding a mechanism that provides first-class gates for specific features at different levels (dev, alpha, beta, etc).  However, this is not implemented yet.  In the absense of this mechanism, we need to decide how to we will support fields like this.

I suggest the following in the interim until the gating mechanism is available:

1.  We should name fields for alpha features starting with `Alpha` (`alpha` in the serialization)
2.  Godoc for these fields should indicate that they are alpha, that there may be bugs, and that no guarantee of backward compatibility exists
3.  We should gate the use of these fields behind a flag to the API server and controller manager; the controller manager is needed because the fields may be created out of band to the API server via TPR
4.  When the field graduates to beta, we should rename the field by removing the `Alpha` part of the field name

**Comment by duglin** [comment]
Seems ok. One question though on the flags to enable the alpha features... when the feature changes the behavior of our code then I think that makes sense.  But, when the feature is 100% additive do we really need to require people to add a flag to enable it?  Shouldn't them adding the alpha-named field to the resource be sufficient?  Not a blocker either way - just looking for a way to make life easier for people when they want to play with it.  Ran into this with the podpreset stuff today - and it was kind of cumbersome that it wasn't enabled by default since its 100% additive, and it then required additional education on how to turn it on (after I figured out that's what I needed to do).

**Comment by pmorie** [comment]
@duglin 

> But, when the feature is 100% additive do we really need to require people to add a flag to enable it?

It's probably best to talk through a couple specific examples - I'm wondering if you're thinking about something like the OSB context profile.

**Comment by duglin** [comment]
yea, "context" is an example of it, but what made me think of this yesterday was when I was playing with the PodPreset admission controller. Things didn't work for me at first and it turned out it was because I didn't go out of my way to enable the A.C. Easy fix but seemed like kind of an unnecessary burden when I have to go out of my way to hit the feature at all by trying creating a PodPreset resource.  So, while the admission controller case might be a bad example because (and I'm not 100% sure here) but we may not have any admission controllers enabled by default, your issue maybe me wonder if in the general case we could lower the pain for our users by enabling alpha features by default when the users have to go out of their way to bump into the new code anyway.  This of course doesn't apply to features that will be optional when we hit v1.0 - in those cases it makes sense to expose/test the on/off mechanisms along with the feature itself.

**Comment by pmorie** [comment]
I am starting to think that this is not an issue (due mainly to our apparent consensus on #994).  I don't think that we should have any alpha fields in the beta API, period.  I'm going to close this; someone can re-open or open a new issue if they have a specific case that they can point to.
