### ISSUE TITLE
canary images aren't being pushed on each build of master

### ISSUE THREAD

**Issue by krancour** [kubernetes-incubator/service-catalog#766]
https://quay.io/repository/kubernetes-service-catalog/apiserver?tab=tags

Currently, the canary was last built 6 days ago and we've merged many PRs to master since then.

This needs to be fixed, as the expectation is that canary images represent what had been built from the current head of master.

**Comment by arschles** [comment]
Looking at this, I see that we set `tags: true` on the `.travis.yml` file (https://github.com/kubernetes-incubator/service-catalog/blob/master/.travis.yml#L16). It looks like that precludes us from using any `branch:` qualifiers.

Looks like I broke this a while ago, not sure why we were building canary images since then.

**Comment by krancour** [comment]
I was just about to link you to that.
