### ISSUE TITLE
Push the build image to quay

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#778]
Instead of continually building & caching the `scBuildImage` docker image on our local machines, it's probably a good idea to push it to our quay repo and then pull it to all our machines.

**Comment by krancour** [comment]
@arschles generally, I agree. That's how you and I are accustomed to having seen this done in the past, but in those cases, there was one common containerized development environment shared by many projects. That's not the case here. Although it does slow things down a bit, a huge advantage to how thing are currently is that a PR that requires changes to the containerized build environment (e.g. a new tool is needed), that change can be bundled _into_ the PR, instead of having to coordinate multiple PRs to first update the development environment and _then_ utilize those updates.

But if you have a workflow in mind that can support that while still taking advantages of a pre-built build image, I'm 👍 on that. Any specific thoughts about how that can be done?

**Comment by MHBauer** [comment]
It seems like the primary concern this addresses is reproducible builds in the future using exactly the tools that existed at the times of the original builds.

**Comment by arschles** [comment]
There are still quite a few open questions on this issue, so I am removing it from a milestone until we get back to discussion

**Comment by MHBauer** [comment]
This could also be a good thing for prow to have.
