### ISSUE TITLE
Service Broker bind implementation OpenShift Origin

### ISSUE THREAD

**Issue by maleck13** [kubernetes-incubator/service-catalog#792]
Hey Guys,
I opened the following issue against origin. https://github.com/openshift/origin/issues/14003 . 
It is more of a query and set of questions about the service broker in OpenShift Origin, but I was directed to open an issue here instead. If this is the wrong place, apologies in advance and thanks for any info you can give. 

Below is the issue I created: 
I realise the service broker implementation in Origin is currently just a tech preview, but I have some questions about the bind implementation.
Currently, the bind implementation seems very simple. Correct me if I am wrong, but from reading the code I believe it simply looks for a basic auth secret plus the cluster ips of the services and returns those.
Are there plans to allow for creating many bindings to one service or to allow creating a binding to something like a mongodb or mysql db in which a new set of credentials plus the database is created? Or would you expect other service brokers to provide this functionality?
To support this kind of binding, I imagine, is complex as you have multiple protocols and requirements.
I have been looking at building a broker that works with OpenShift (hence my interest) . One way I considered solving the problem of multiple bindings and protocols was to use a job with an image that would contain the required logic to create the binding. My service broker would then launch this job passing in the "admin" credentials that were created / specified when the service was first provisioned (this could be a secret also) and then check the status of the job to see had it succeeded. The job could be responsible for not only creating the binding but also creating a secret in the specified namespace. Likely there is a much better way to achieve this but wanted share my thoughts. Interested to hear any thoughts or plans in this area.

**Comment by duglin** [comment]
@maleck13 its important to look at this through the lens of the OSB API spec and not one particular implementation. With that in mind, I'm not 100% sure I'm following your questions, but let me try to restate them and see if I'm close:

- Can there be multiple bindings to the same service instance? Yes, and typically each binding will get a different set of credentials but this is not a requirement and each service broker will decide this.
- Can the same app bind to the same service more than once? The spec is silent on this so from the spec's perspective, as of now, I think the answer is yes. However, the main implementation today (CF) will not allow this. I didn't check the code but I think Kube's version will allow it - but I'm not sure if that's a mistake or not - I'll open an issue so we make it a concrete decision one way or the other.
- you said "The job could be responsible for not only creating the binding but also creating a secret in the specified namespace" and I think you're mixing concepts. The service broker will be responsible for creating the service instance itself and returning a json blob with the binding/creds. That's where its job stops. Creating secrets, in the right namespace, from that json blob will be up to Kube.

Does that help at all?

**Comment by maleck13** [comment]
@duglin Thanks very much for your reply.
You are correct, I am talking more about a specific implementation of a service broker. Is it possible for you to point me at the code for implementations you are talking about?

On point 1 and 2 these make sense.
On point 3 I think I need to clarify further what I was getting at, and as you mention it is more likely an implementation detail. Let me attempt to clarify a little.

I am interested in a service broker that runs in OpenShift/ Kubernetes that understands how to provision services to the cluster where it is running (perhaps I am  just describing what this project is).  In the previous comment, I was attempting to come up with a pattern that would allow these service to be part of the catalog of such a service broker but also make adding new services as easy as possible. 
The half baked concept I tried to describe above (sorry for the confusion) was to have a bespoke "binding" image provided per service definition that would encapsulate the implementation details of the protocol and api (think mysql, mongo, amqp) and have this image used with something like a kubernetes job that the service broker would create via the api in a given namespace, so in effect delegating the details to the provided "binding" image defined with the service. This is likely a terrible idea and has lots of complexity. I guess I am looking for some opinions on how something like this might be achieved.
Is there a concept of many smaller service brokers aggregating their catalog into one large catalog? Again if I am describing what this project already is, apologies.

**Comment by krancour** [comment]
@maleck13 I'm reading through your original questions and your follow-ups to @duglin and I am getting the sense that some clarification on the roles and responsibilities of 1. service catalog and 2. brokers might help you.

Let's start with the brokers, because, conceptually, that's the easier place to start. Brokers are just bits of software that can create instances of some sort(s) of service _and_ hand out creds for those services. Brokers should adhere to the OSB spec (formerly the CF service broker API). This spec defines the RESTful interface for a broker. All brokers must implement this interface, and that's what guarantees compatibility with CF or with the k8s service catalog.

With respect to brokers, _everything else_ is an implementation detail. I'll give some examples.

1. Where the broker itself is hosted is an implementation details. It could be within the cluster. It could be elsewhere. It doesn't matter.

2. A broker could provision services _within_ a cluster (i.e. services that are _hosted_ within the cluster). Equally, a broker could provision services _outside_ a cluster. For instance, a broker could provision a Postgres database in RDS.

3. A broker could implement "provision" as it sees fit. Revisiting the idea of provisioning a Postgres database: A broker could provision a whole new RDBMS in RDS. _Or_ a broker could merely provision a new database within an _existing_ RDBMS (which in turn could be in RDS... or elsewhere).

4. A broker could create _new_ credentials for each binding. Equally, it could just hand out copies of a single, common set of credentials.

All of the above are implementation details. These details don't matter to the k8s service catalog as long as the broker speaks OSB. 😄 

Now... on to the subject of what the k8s service catalog actually does. Really, it only _adapts_ OSB brokers to a k8s-native workflow.

If you want an instance of some type of service, you create a new `instance` resource. The service catalog will translate that into the appropriate RESTful calls out to the correct broker.

If you want credentials for the above instance, you create a `binding` resource. The service catalog will translate that into the appropriate RESTful calls out to the correct broker. Such a request returns credentials and/or other connection details-- for instance, database connection string / URL. (Again-- _how_ the broker created those and whether they're unique to the requestor is the broker's choice.) The service catalog will squirrel these details away in a secret. An application pod can then mount that secret or use the k8s downward API to inject values from the secret into environment variables.

That's pretty much it.

I'll answer this particular question directly:

> Is there a concept of many smaller service brokers aggregating their catalog into one large catalog? 

Yes. Very much so. That's how all of this is supposed to work. Recall that brokers are just bits of software and they could live anywhere-- on or off-cluster. When a _cluster operator_ (some ops guy with responsibility for a given cluster) wants to expose the catalog of a given broker in his/her own cluster, he/she creates a `broker` resource that points at the URL of the broker in question and provides whatever creds the broker itself requires for authn/authz. When the service catalog connects to the broker, the first thing it will do is query the broker for all the services it offers. Service catalog _adds_ all of those to itself. You could query them by listing all `serviceclasses`.

From there, it's out of the cluster operator's hands and a developer would follow the provision / bind workflow that I have already described.

Does this help clarify architecture, roles, responsibilities, etc.?

**Comment by maleck13** [comment]
@krancour This was very useful thank you, it has reenforced my own understanding of the broker and clarified the role of the service catalog.

**Comment by krancour** [comment]
@maleck13 happy to have helped. 😄
