### ISSUE TITLE
Determine correct place to reject delete/update to instance with ongoing async op

### ISSUE THREAD

**Issue by vaikas-google** [kubernetes-incubator/service-catalog#804]
When a Service Instance has an ongoing asynchronous operation ongoing the platform (in our case controller/service catalog) must ensure no changes are allowed to that Service Instance and it can not be deleted. So, we need the correct place to check for the status of the service and reject the request for updates / deletes if the operation is in process:
https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/apis/servicecatalog/types.go#L212

It seems like there are (at least) two places that this could happen.
1. Implement RestDeleteStrategy/RestUpdateStrategy and check the status there and reject the request
2. Implement Admission Controller

I've found it difficult to find a guideline on which of these (or if there's a better way) to go about achieving what we want to do. I'd be happy to get some pointers if I missed them, or general guidance on how to tackle this.

**Comment by pmorie** [comment]
A couple observations / background infos:

1.  This is another how-do-i-develop-kubernetes question, for which we do not yet have doc
2.  I seem to recall that @MHBauer had opened a pull request beginning some how-to-write-an-API-server doc, which would be the kind of document I would try to build this onto, but I cannot locate it now

So, specifically regarding the question here - this is the type of mechanism that admission controllers are useful for implementing.  Using an admission controller keeps the registry implementation for a resource simpler because we can keep it free from business logic (thought it may be arguable that business logic is present to some extent in some registries).  I know one concern you had about using admission controllers is that users can choose which controllers to run, and thus someone could get into a situation where they had incorrect behavior because they didn't run the right admission controller.  While you're correct that admission controllers are user selectable, we have a number of features in kubernetes that depend on admission controllers to function correctly (examples: [LimitRanges](https://kubernetes.io/docs/tasks/configure-pod-container/limit-range/), [quotas](https://kubernetes.io/docs/concepts/policy/resource-quotas/)). So, admission controllers can be used safely for stuff like this.

**Comment by pmorie** [comment]
Also, we should just start writing the doc I referred to in the above comment now, maybe in a gist or a separate repo that we can collaborate on together and merge it with whatever may be in progress later.

**Comment by pmorie** [comment]
cc @derekwaynecarr since he is the creator and owner of admission controllers in k8s

**Comment by derekwaynecarr** [comment]
I am trying to see if there is any other situation where we block a change to spec due to the state of status.  At a glance, I don't like the idea as spec is the desired state we want to realize and should be somewhat disjoint from status.  If I understand correctly, we want to protect against spec changes if an async op is in flight.  Could we model this differently?

For example, could we have a lock semantic on the spec which is only modifiable via a instance/foo/lock subresouce which would toggle a field in the spec?  Privilege to perform the lock action would only be extended to the controller?  The lock is then taken prior to starting an async op in controller?  Then conflicting spec mutations can be restricted during normal validation?  It would be similar to how /pod/foo/bind sets nodeName and how we can then restrict edits in validation when nodeName is not nil?

**Comment by duglin** [comment]
I agree that I'm not sure we should be solving this issue via blocking end-user's actions.  IMO the statement in the OSB API spec about blocking concurrent requests (which I'm in the process of changing) should only impact the Platform->Broker interactions, not the user->Platform interactions for us.  In some platforms where they're more of a synchronous processing model it may make sense to block the user, but kube is really an async model. This means that it should be up to the svc-cat controller to block/serialize its requests to the broker - while the user is unaware of it.

So, do we need a locking mechanism at all? Or simply a flag on in the status section that says "we have an outstanding request to the broker" and the controller will not try to take any additional reconciliation action (that involves talking to the broker) while that flag is true.

Note that this blocking isn't just an async-op thing - it can happen during the processing of any request to the broker if the platform receives more than one action on the same resource at the same time.

**Comment by vaikas-google** [comment]
Right, so the original request / investigation was based on the Spec as written. We are in the process of changing the spec so that we have more leeway in implementing it. Let's assume that goes through. So, we have the flag already in status, and I assume we can use that as our 'lock' as @duglin says above. That is how it is already used to prevent other things from happening at the same time.
When you say 'normal validation', are those the Rest[Update|Delete]Strategy, or something else?
And is the proper way to signal the error in that case using the field.ErrorList, or again something else?

Thanks!!

**Comment by duglin** [comment]
is this related to (or even a dup of) https://github.com/kubernetes-incubator/service-catalog/issues/781  ?

**Comment by vaikas-google** [comment]
@duglin @pmorie Closing this since I believe this has been done. Reopen if you don't think so.
