### ISSUE TITLE
Send bind_resource.app_guid on bind requests

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#818]
The spec seems to indicate that a bind request body should contain a `bind_resource.app_guid` field, although it is not explicitly marked as being required:

https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#body-5

If this is actually required, we should send it.

**Comment by MHBauer** [comment]
I did not understand bindings besides credentials when I originally started looking at the spec.

If we're claiming to be a conformant broker, I thing we have to support `log drain`, `route service`, `volume service` bindings.

We do not currently send any of the required responses. 

@duglin are these three other types of bindings CF-ish, or is it something we need to be concerned about implementing?

**Comment by MHBauer** [comment]
Can we selectively reject services on service brokers that have a `requires` field?

**Comment by duglin** [comment]
I do not think we are required to support all 3, but the spec doesn't come right out and say that either. We need to fix that.

IMO the optional-ness of app_guid is more for cases where there is no app at all and the service isn't meant to be related to just one app.   While app_guid is not required I think we should send it- we just need to find the right value to send.

**Comment by duglin** [comment]
Tagging this as 0.1.0 because I think we need this in the model and how (what) we store it could change the model.

**Comment by arschles** [comment]
This still has some questions that need answering in the spec. We need to solve by 0.1.0

**Comment by pmorie** [comment]
I think that for now, we should not allow binding to any service that has a non-empty `Requires` field.

**Comment by duglin** [comment]
I agree but I'm not sure if it relates to this issue since this is about cred-bindings which may (or may not) also be other types of bindings (via Requires)

**Comment by duglin** [comment]
Based on our decision to not include any kind of PodPreset thing in our beta, I don't think we have any notion of an app to which we can associate the Binding resource to.  However, as part of that discussion we sort of landed on the idea that our Binding resource is really more like a request to get creds and create a secret (see the entire ServiceInstanceCredentials discussion here: https://github.com/kubernetes-incubator/service-catalog/issues/1060 ).  So, with that I think there are two choices:
1 - continue to send the namespace GUID for app_guid so that the broker is provided at least some level of "grouping" or "association". After all, secret are scoped to namespaces not apps.
2 - send nothing

I think a lot of this depends on how "firm" we think our decision is to split the PodPreset kind of thing from Binding. Meaning, if we're sure that we will never want to include a PP type of thing in a Binding and Bindings are really "create InstanceCredential" requests, then I think option 1 is the right approach. Option 2 only makes sense to me if we're still in doubt about the question. But my sense from the group is that we're pretty sure of this change.

I'll add this to an upcoming design call, but my proposal is:
close this with no action - keep sending the namespace GUID for app_guid on the binding request.

**Comment by duglin** [comment]
On today's design call we agreed to CWNA (close with no action) and we can reopen if we get new data/usecases that cause us to rethink it.
