### ISSUE TITLE
Jenkins should not run E2Es with colorization

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#844]
...which makes the output difficult to read.  We should use the `--noColor` option in ginkgo for jenkins runs.

**Comment by kibbles-n-bytes** [comment]
As we are not running the `ginkgo` CLI, there did not seem to be a clearly documented way to stop the colorization using the ginkgo library from within the e2e tests. I figured instead of disabling the colorization, then, we could just have it handled correctly by Jenkins. I just submitted a PR ( #856 ) that does this.
