### ISSUE TITLE
Validate that External ID fields do not change

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#868]
These should be immutable according to the OSB API spec.

**Comment by mdshuai** [comment]
@pmorie Are you working on this,If not, Could you mind assign this to me? thanks.

**Comment by MHBauer** [comment]
@mdshuai still interested?

let's try the bot

/assign @mdshuai

**Comment by MHBauer** [comment]
@pmorie are these changes on updates for all current structs? Should this use the `ValidateUpdate(old, new)` code? 

On the actual implementation, should we reject updates or do the silent copy from old to new? Something similar happens when trying to change a spec while changing the status.

**Comment by pmorie** [comment]
This may not be an issue, depending on the resolution of #802

**Comment by duglin** [comment]
whether we end up using the human name or the ID as the Kube meta.name I believe that the exernalID should never be allowed to change on our resources. If the ID were to ever change (due to a re-list of the broker) then the result of that should be a new resource being created in svc-cat, not a changing of the externalID.

This means we could either:
1 - not worry about it and assume our controller would never do such a thing
2 - add a check to block it so that a) we block a bug in our controller, and b) we block a user from doing something they shouldn't be doing

Proposal: option 2

**Comment by pmorie** [comment]
It seems from discussion on the catalog and architecture lists that we will probably not use the OSB ID as the name, so this is probably still and issue, but depends on the outcome of #802.

**Comment by pmorie** [comment]
Solved by our naming convention choice for now and #1249
