### ISSUE TITLE
Add API surface for broker API version and alpha OSB feature support

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#982]
Split out from #971 

There should be API fields for setting the version of the OSB API that a broker supports and whether that broker allows alpha features to be enabled.  Note that alpha feature support is probably only meaningful for brokers that work with the most recent version of the API.  The OSB client already supports pinning to a version and has an alpha features flag, so this should just be a matter of adding a couple fields to the Broker's spec:

```go
type BrokerSpec struct {
  // other fields omitted
  OSBSettings *OSBSettings `json:"osbSettings,omitempty"`
}

type OSBSettings struct {
  // APIVersion is the version of the OSB API to use to communicate with this broker.
  // If empty, the latest version of the API will be used.
  APIVersion string `json:"apiVersion,omitempty"`

  // AlphaFeatures characterizes the use of alpha features for this broker.  Unless
  // the value of this field is "Enabled", alpha features are disabled.
  AlphaFeatures *OSBAlphaFeatures `json:"alphaFeatures,omitempty"`
}

type OSBAlphaFeatures string

const (
  OSBAlphaEnabled OSBAlphaFeatures = "Enabled"
  OSBAlphaDisabled OSBAlphaFeatures = "Disabled"
)
```

**Comment by MHBauer** [comment]
Do we still need the `enable-osb-api-context-profile` flag?

**Comment by pmorie** [comment]
We should remove it as part of this, or make it a dummy a remove it in beta (don't want to break anyone currently setting it).

**Comment by duglin** [comment]
For simple cases like this where there's a new property that's 100% backwards compatible I agree that we don't need a flag to turn it on, we can just always send it to the broker w/o any harm.  No dummy flag either

**Comment by duglin** [comment]
re: #810 - I think a global flag to control api version might be nice, but then allow for it to be specified on a per-broker (at registration time) might be good too.

**Comment by pmorie** [comment]
In this case, I think we should keep the existing CLI flag for sending the context and make it inert and then remove it on 0.1.0.

There should be an admission controller that sets the default version on the broker resource so that it's explicit once the object is created.  This could be driven off a flag.

**Comment by pmorie** [comment]
I am thinking now that the 'if empty' behavior of using the latest API version is not going to be what people want at all.  There should be a per-broker explicit version that is used (which we can set from a configurable default).

**Comment by MHBauer** [comment]
> There should be an admission controller that sets the default version on the broker resource so that it's explicit once the object is created. This could be driven off a flag.

Can an admission controller change objects? Should the defaulters do that?

**Comment by pmorie** [comment]
> Can an admission controller change objects? Should the defaulters do that?

Admission controllers can mutate objects, yes.  I would prefer an admission controller because there is no plumbing to expose config items to defaults, and defaults should be things that do not vary anyway.

**Comment by MHBauer** [comment]
I'll start this tomorrow if no one else has.

**Comment by MHBauer** [comment]
@pmorie I'll pick this one up now. Separately from #1014. @duglin 

Options:
 1. Require a version be set when creating the broker on the incoming broker definition
 1. require a version to be set before storage, but use defaulting when an incoming broker does not have the field set. 
 1. completely optional field, default to whatever if set when starting apisever, or most recent version in the library. (I do not like this one)

I think we should require the field, and/or have an extra flag/config that says explicitly what happens in the "I didn't set it, and now it's changing" case. Such as, --auto-header-version

svc-cat upgrade behavior only applies with 2 & 3
 1. use whatever was persisted when the broker was initially added
 2. automatically upgrade osbapi versions as it is restarted and gains new higher levels.

**Comment by pmorie** [comment]
I want (2) - make it a field on the broker, set it during admission.  I think the behavior of the controller should be purely based on the broker's spec.  IE, there should be no 'unset' version that results in a config-item of the controller determining which version to use.

**Comment by duglin** [comment]
So imagine an env where there are 500 brokers and each time the OSB API spec (and svc-cat) is updated we want to force people to update all of their brokers to some version number that they probably don't even track?

**Comment by duglin** [comment]
one thing to think about is that the version number on osb api is not like the version numbers in kube. In kube they don't change that often (v1 of pod is long lived).  But for osb api we expect the version number to change often - true, stay within the v2.x range, but still it'll change.

**Comment by duglin** [comment]
Based on the discussions here I think we need a concrete proposal for the group to consider rather than a list of options.

My preference would be (mainly due to https://github.com/kubernetes-incubator/service-catalog/issues/982#issuecomment-315149839 ) would be:
- allow for apiserver admin to pick a default OSB version, not specified == latest OSB version svc-cat supports
- allow for a per-broker OSB version to be specified during broker registration, not specified == use apiserver's default OSB version value

But either way, @MHBauer since you volunteered to pick this one up, you should probably pick the solution you want the group to consider.

**Comment by pmorie** [comment]
> allow for apiserver admin to pick a default OSB version, not specified == latest OSB version svc-cat supports

This is not the kube way, really.  We need to have the information represented explicitly in the API surface for the broker resource.  Users do not want behaviors invisible to them (ie, latest whatever version happens to be configured)

> allow for a per-broker OSB version to be specified during broker registration, not specified == use apiserver's default OSB version value

This one is more actionable, but requires an admission controller to set the default value, which may be fine.

**Comment by pmorie** [comment]
> So imagine an env where there are 500 brokers and each time the OSB API spec (and svc-cat) is updated we want to force people to update all of their brokers to some version number that they probably don't even track?

Yes - maybe eventually we could add a command to bulk update everything.

**Comment by duglin** [comment]
I think my point was missed. I don't think people should have to even think about it unless there's a reason to and they want to lock things down to a certain version - either globally or per broker. Otherwise the default should be the latest version of OSB.  This may change if we ever get to a v3 but for now I think this is the least amount of pain for our users.

**Comment by MHBauer** [comment]
# Control OSB API Version Per Broker

## Abstract

Allow configuration of the OSB API version used to talk to a broker on a per
broker basis.

## Motivation

Currently, service catalog has a flag to configure the version of OSB API used
to talk to all brokers. For compatibility, it is desired that a field is added
to the Broker object. This field will contain the version of the OSB API used to
talk to that specific broker.

## Proposed Design

 - Add new field `APIVersion` to BrokerSpec.
 - Add new AdmissionController to set the field to a default if unset.
 
### Default OSB API version

Pick one of SemVer or EmptyString

#### SemVer

If the field is unset, an admission controller will set it to the semver value
`2.*`.  The `--osb-api-preferred-version` flag will be used at runtime to
determine the actual value used when communicating with the broker.

#### Alternate EmptyString

If the value is unset or an empty string, it is marked as optional value, and
the controller, finding a blank value, will use the value of the
`--osb-api-preferred-version` flag on the APIServer.


### Service Broker 

```go
type BrokerSpec struct {
    ...
    // APIVersion is the version of the OSB API to use to communicate with this broker.
    // If empty, the latest version of the API will be used.
    APIVersion string `json:"apiVersion,omitempty"`
    ...
}
```

### AdmissionController

The admission controller will set the APIVersion value on the Broker if it is unset.

## Tradeoffs
### Pro
 - using semver
   - on upgrade of supported version, nothing has to be done to existing objects.
   - the value must exist
   - if accidentally unset to a blank value, this is an error (in mind is
     automated tooling doing string interpolation that may interpret some string
     error as an empty string. bash does this for certain variable references.)
 - blank value
   - on upgrade of supported version, nothing has to be done to existing objects.
### Con
 - semver
   - need to parse and handle semver in service catalog (pull in a dependent
     library)
 - blank value
   - user may have set a blank value on accident, and we can't know

## Later

Major version upgrades.

**Comment by duglin** [comment]
We may be overthinking this one.  A couple of things...

We already have a version string in our UX, right now its `servicecatalog.k8s.io/v1alpha1`. If we ever end up having a v3 of OSB API then its because the semantics of how to talk to a v3 broker will be so different from a v2 broker that we're going to need to create a `servicecatalog.k8s.io/v2` Broker resource to properly convey those differences. The addition of a `osb-api-version` type of property/flag seems unnecessary and redundant. This seems to me to be the proper "kube way" to deal with major design/semantic changes.  So, IMO we can ignore major version changes as part of this discussion.  

Within the scope of v2 I think its important to remember that everything must be backwards compatible. I was talking with Shannon last night asking about how CF deals with things like the possibility of needing to "pin a broker to a certain OSB API version" and the short answer was "they don't and they've never needed to because everything has always been backwards compatible".  That then begs the questions: what would have to happen for that rule to be broken? and what would happen if it was?

In order for us to introduce a non-backwards-compatible change to the spec we would need to: 1) have everyone in the OSB API wg miss it, and 2) all of our testing (for both CF and Kube) would have to miss it as well. Possible, but probably not a very common occurrence - and history has already proven this.

So, then what about if it did happen anyway? There would be a few things that would happen: 1) the deployment of Kube that noticed it would probably roll back their upgrade of svc-cat to the previous version so they would be un-stuck, 2) we'd be notified of the bug and work on putting out a point-release with a fix ASAP. Whether that's just a code change in svc-cat or an OSB API spec change, it would have to happen pretty quickly because we've violated our versioning contract.

The point being, this situation is no different than any other change that goes into Kube that might break people in a non-backwards-compatible way and we deal with that by quickly releasing a new Kube version with a fix. We don't offer a "version" flag that allow people to "pin" themselves to the previous version of the code. 

**Net: I don't think we need a osb-version flag at all and I think we should CWNA.**

As for an 'alphaFeaturesFlag', I think we should discuss that separately since that's an orthogonal discussion.
