### ISSUE TITLE
What happens on service class name conflicts?

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#999]
When you add a `Broker` that returns a service name `a` and there is already a `ServiceClass` called `a` in the system, there will be a conflict. I believe that, given the OSB spec that we have now, the catalog should add a suffix indicating the broker name (i.e. `a-broker2`) to the second service class. In the future, we may want to push some naming conventions upstream to the OSB spec that would solve this in a more elegant way.

**Comment by nilebox** [comment]
>  the catalog should add a suffix indicating the broker name (i.e. a-broker2) to the second service class

Agree, but it probably should be prefix instead of suffix (as usually the convention is that prefix is more generic, and suffix is more specific). Also see the comment for similar problem also suggesting prefix https://github.com/openservicebrokerapi/servicebroker/issues/249#issuecomment-310997977

**Comment by duglin** [comment]
+1 to a prefix but I'm wondering if we should do it all the time instead of just on a conflict because otherwise we'll get into the position of "whoever gets there first wins" and then one will look more "real" or "preferred" than the others.

Obviously we should let an admin modify the names as needed but by default we might as well always prefix them.

Or allow for a flag but make it a simple boolean. Meaning, no flag(or false) we do as we do today (and what CF does) - on conflict generate an error and stop ; or flag is set (true) and we'll always prefix.

**Comment by duglin** [comment]
Just for some background, as this topic came up with some customers during the CF Summit a few weeks ago, CF's current approach is to generate an error and stop.  This works ok because normally the name that devs will see is (sort of) a marketing concern and the service provider will most likely want to have a say over what name appears. For example, company "BigJohns" may not be want their service to show up as "bj-broker-mongo" because the Kube admin decided to give the broker the name "bj-broker". So typically we would expect the service provider to give more unique names to their services such that conflicts do not happen - and they have control over the name.

This is why the current approach is ok for now. Having said that, allowing an admin to easily modify the names if necessary during the population of the catalog (via an optional flag) would be good.

**Comment by bmelville** [comment]
Hey, just trying to understand this problem a little more: is this a problem with key collision, or a problem of ambiguity at provisioning time?

Long ago when thinking about this issue, I got the impression that it would be beneficial to allow for collisions (e.g., including broker name in the key), and also to allow for disambiguation at provisioning time through an optional syntax to fully specify the class name.

For example, in a non-ambiguous case, this is okay:

```
apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Instance
spec:
  serviceClassName: foo-class
```

but in an ambiguous case, it would error and require something like:

```
apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Instance
spec:
  serviceClassName: foo-broker/foo-class
```

**Comment by duglin** [comment]
I think https://github.com/kubernetes-incubator/service-catalog/issues/802 is related because if we don't end up using the names as keys/kube-names then the problem changes.

**Comment by arschles** [comment]
@bmelville the way I see it, the problem is with key collision. I agree that #802 may obsolete this issue. I'll comment in there.

**Comment by MHBauer** [comment]
@arschles @duglin @ash2k I think this issue is closable now that we use GUIDs all over and have both k8s names and external IDs?
